# Generated by Django 5.1.5 on 2025-04-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.FloatField(null=True, verbose_name='Вес')),
                ('price', models.IntegerField(null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ArmorCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория доспеха',
                'verbose_name_plural': 'Категории доспехов',
            },
        ),
        migrations.CreateModel(
            name='Chars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_quantity', models.IntegerField(verbose_name='Количество костей')),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('use_time', models.CharField(max_length=40, verbose_name='Время накладывания')),
                ('distant', models.FloatField(verbose_name='Дистанция')),
                ('components', models.TextField(blank=True, verbose_name='Компоненты')),
                ('duration', models.CharField(max_length=40, verbose_name='Длительность')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('higher_level_description', models.TextField(blank=True, verbose_name='При повышении уровня')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
            },
        ),
        migrations.CreateModel(
            name='DamageTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Примеры')),
            ],
            options={
                'verbose_name': 'Тип урона',
                'verbose_name_plural': 'Типы урона',
            },
        ),
        migrations.CreateModel(
            name='Dices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Кость')),
            ],
            options={
                'verbose_name': 'Кость',
                'verbose_name_plural': 'Кости',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название уровня')),
                ('level_number', models.IntegerField(verbose_name='Номер уровня')),
                ('level_description', models.TextField(blank=True, verbose_name='Описание уровня')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='Источник')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, upload_to='photos/sources/%m/%Y/%d/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='WeaponClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Класс оружия',
                'verbose_name_plural': 'Классы оружий',
            },
        ),
        migrations.CreateModel(
            name='WeaponsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория оружия',
                'verbose_name_plural': 'Категории оружий',
            },
        ),
        migrations.CreateModel(
            name='WeaponsFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Свойство оружия',
                'verbose_name_plural': 'Свойства оружий',
            },
        ),
        migrations.CreateModel(
            name='ArcaneFocuses',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.items')),
            ],
            options={
                'verbose_name': 'Магическая фокусировка',
                'verbose_name_plural': 'Магические фокусировки',
            },
            bases=('playersbook.items', models.Model),
        ),
        migrations.CreateModel(
            name='DruidicFocuses',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.items')),
            ],
            options={
                'verbose_name': 'Фокусировка друидов',
                'verbose_name_plural': 'Фокусировки друидов',
            },
            bases=('playersbook.items', models.Model),
        ),
        migrations.CreateModel(
            name='HolySymbols',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.items')),
            ],
            options={
                'verbose_name': 'Священный символ',
                'verbose_name_plural': 'Священные символы',
            },
            bases=('playersbook.items', models.Model),
        ),
        migrations.CreateModel(
            name='DamageOnLevel',
            fields=[
                ('damage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.damage')),
                ('level', models.IntegerField(verbose_name='Уровень')),
            ],
            bases=('playersbook.damage', models.Model),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.damagetypes', verbose_name='Тип урона'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_dice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.dices', verbose_name='Кость урона'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Пример использования')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.chars', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.sources', verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='SubClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_class_name', models.CharField(max_length=40, verbose_name='Подкласс')),
                ('sub_class_description', models.TextField(blank=True, verbose_name='Описание подкласса')),
                ('image', models.ImageField(blank=True, upload_to='photos/classes/sub_classes/%m/%Y/%d/')),
                ('levels', models.ManyToManyField(related_name='subclass_levels', to='playersbook.levels')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.sources', verbose_name='Источник')),
                ('spells', models.ManyToManyField(blank=True, related_name='sub_class_spells', to='playersbook.spells', verbose_name='Заклинания')),
            ],
            options={
                'verbose_name': 'Подкласс',
                'verbose_name_plural': 'Подклассы',
            },
        ),
        migrations.CreateModel(
            name='WeaponsTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.sources', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Оруженый прием',
                'verbose_name_plural': 'Оружейные приемы',
            },
        ),
        migrations.CreateModel(
            name='Armors',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.items')),
                ('AC', models.IntegerField(verbose_name='КД')),
                ('AC_add', models.CharField(blank=True, max_length=100, verbose_name='Дополнение к КД')),
                ('strength', models.IntegerField(blank=True, verbose_name='Минимум силы')),
                ('stealth', models.BooleanField(default=False, verbose_name='Помеха скрытности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.armorcategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Доспех',
                'verbose_name_plural': 'Доспехи',
            },
            bases=('playersbook.items', models.Model),
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.items')),
                ('use', models.TextField(blank=True, verbose_name='Использование')),
                ('create', models.TextField(blank=True, verbose_name='Создание')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.chars', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
            bases=('playersbook.items', models.Model),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='photos/classes/%m/%Y/%d/')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('first_level_hits', models.IntegerField(verbose_name='Хиты на первом уровне')),
                ('another_levels_hits', models.IntegerField(verbose_name='Хиты на следующий уровнях')),
                ('weapons_ownership_add', models.CharField(blank=True, max_length=100, verbose_name='Дополнение к владению оружием')),
                ('skills_ownership_add', models.CharField(blank=True, max_length=100, verbose_name='Дополнение к владению навыками')),
                ('tools_ownership_add', models.CharField(blank=True, max_length=100, verbose_name='Дополнение к владению инструментами')),
                ('armors_ownership_add', models.CharField(blank=True, max_length=100, verbose_name='Дополнение к владению доспехами')),
                ('becoming', models.TextField(verbose_name='Становление')),
                ('beginning_equipment', models.TextField(blank=True, verbose_name='Стартовое снаряжение')),
                ('armors_ownership', models.ManyToManyField(blank=True, related_name='classes_armors', to='playersbook.armorcategories', verbose_name='Владение доспехами')),
                ('main_chars', models.ManyToManyField(related_name='classes_main_chars', to='playersbook.chars', verbose_name='Основная характеристика')),
                ('saving_throws', models.ManyToManyField(related_name='classes_saving_trows', to='playersbook.chars', verbose_name='Спасброски')),
                ('spells', models.ManyToManyField(blank=True, related_name='class_spells', to='playersbook.spells', verbose_name='Заклинания')),
                ('hit_dice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.dices', verbose_name='Кость хитов')),
                ('levels', models.ManyToManyField(related_name='class_levels', to='playersbook.levels', verbose_name='Уровни')),
                ('skills_ownership', models.ManyToManyField(blank=True, related_name='classes_skills', to='playersbook.skills', verbose_name='Владение навыками')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.sources', verbose_name='Источник')),
                ('sub_classes', models.ManyToManyField(related_name='subclasses', to='playersbook.subclasses', verbose_name='Подклассы')),
                ('weapons_ownership', models.ManyToManyField(blank=True, related_name='classes_weapons', to='playersbook.weaponscategories', verbose_name='Владение оружием')),
                ('tools_ownership', models.ManyToManyField(blank=True, related_name='classes_tools', to='playersbook.tools', verbose_name='Владение инструментами')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.items')),
                ('damage_dices_quantity', models.IntegerField(verbose_name='Количество костей')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.weaponscategories', verbose_name='Категория')),
                ('damage_dice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.dices', verbose_name='Кость урона')),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.damagetypes', verbose_name='Тип урона')),
                ('features', models.ManyToManyField(blank=True, related_name='weapons_features', to='playersbook.weaponsfeatures', verbose_name='Свойства')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.weaponstechniques', verbose_name='Оружейные приемы')),
                ('weapon_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playersbook.weaponclasses', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружия',
            },
            bases=('playersbook.items', models.Model),
        ),
        migrations.CreateModel(
            name='DamageSpells',
            fields=[
                ('spells_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playersbook.spells')),
                ('damage', models.ManyToManyField(to='playersbook.damage', verbose_name='Урон')),
                ('for_level_update_damage', models.ManyToManyField(blank=True, related_name='damage_to_spell_level', to='playersbook.damage', verbose_name='Увеличение урона')),
                ('on_hero_levels_damage_changes', models.ManyToManyField(blank=True, related_name='damage_to_char_level', to='playersbook.damageonlevel', verbose_name='Урон от уровня персонажа')),
            ],
            options={
                'verbose_name': 'Заклинание с уроном',
                'verbose_name_plural': 'Заклинания с уроном',
            },
            bases=('playersbook.spells', models.Model),
        ),
    ]
